//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Indeks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Create {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Create() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("E_Indeks.Resources.Create", typeof(Create).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Student.
        /// </summary>
        public static string Create_Student {
            get {
                return ResourceManager.GetString("Create Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name is required..
        /// </summary>
        public static string Full_Name_is_required_ {
            get {
                return ResourceManager.GetString("Full Name is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string Grad {
            get {
                return ResourceManager.GetString("Grad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad is required..
        /// </summary>
        public static string Grad_is_required_ {
            get {
                return ResourceManager.GetString("Grad is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks.
        /// </summary>
        public static string Indeks {
            get {
                return ResourceManager.GetString("Indeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks already exists.
        /// </summary>
        public static string Indeks_already_exists {
            get {
                return ResourceManager.GetString("Indeks already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks is required..
        /// </summary>
        public static string Indeks_is_required_ {
            get {
                return ResourceManager.GetString("Indeks is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks must be a 6-digit number..
        /// </summary>
        public static string Indeks_must_be_a_6_digit_number_ {
            get {
                return ResourceManager.GetString("Indeks must be a 6-digit number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosek.
        /// </summary>
        public static string Prosek {
            get {
                return ResourceManager.GetString("Prosek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosek must be a valid number..
        /// </summary>
        public static string Prosek_must_be_a_valid_number_ {
            get {
                return ResourceManager.GetString("Prosek must be a valid number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosek must be between 6.00 and 10.00..
        /// </summary>
        public static string Prosek_must_be_between_6_00_and_10_00_ {
            get {
                return ResourceManager.GetString("Prosek must be between 6.00 and 10.00.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a City.
        /// </summary>
        public static string Select_a_City {
            get {
                return ResourceManager.GetString("Select a City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
    }
}
